### ISSUE TITLE
R report not completing at DH

### ISSUE THREAD

**Issue by zuckerr** [UCCC/CHORDS-QA#11]
Issue from Ken Scott:	I’ve  been running into some issues with the R report running.  I think I’d told you, but previously the VDW option worked for me, even though we work off of views (that start with VDW.dbo).  Currently, neither seems to be running  to completion (not as quickly anyway).  I could just let the machine keep going, but I seem to remember it not taking as long the last go around…

**Comment by vtmacox** [comment]
If the report generated before and it isn't throwing any errors now, this is likely a data issue or an IT issue.  It doesn't seem like a code issue.

**Comment by zuckerr** [comment]
Ok, I'll let Ken know! Thank you!

**Comment by vtmacox** [comment]
I would let the code go for an hour (or even overnight).  If the report doesn't generate, then there is a problem.
