### ISSUE TITLE
Round 2: High Priority: Census_Location checks

### ISSUE THREAD

**Issue by emilybacon** [UCCC/CHORDS-QA#117]
Location: P1, Table 11 and the summary statistics below Table 11

Issue description: Looks like it's only capturing out of state geocodes or saying that all records are out of state. 

Data Partner where issue was detected: All data partners

**Comment by CartWill** [comment]
Added check for Colorado census tract code (08) to list of counties.  In https://github.com/ACCORDSD2VDEV/CHORDS-QA/
