### ISSUE TITLE
Round 2: High Priority: P1 Table 7.11/Figure 1 patients with unknown race/ethnicity

### ISSUE THREAD

**Issue by emilybacon** [UCCC/CHORDS-QA#119]
Issue Location: P1, Table 7.11/Figure 1

Issue description: Will I know we've talked about this table before and you explained to me that it's showing new patients each year, but I think there's still something odd going on with it. This is particularly obvious for a few data partners, like Salud (shown below), that have huge fluctuations in total frequency year over year. What do you make of this? 

<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/ebacon/AppData/Local/Packages/oice_16_974fa576_32c1d314_362e/AC/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel="themeData" href="file:///C:/Users/ebacon/AppData/Local/Packages/oice_16_974fa576_32c1d314_362e/AC/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/ebacon/AppData/Local/Packages/oice_16_974fa576_32c1d314_362e/AC/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

<h2><a name="X8bb539b4f8c8106409fcc822111649fd24d46a1">Table 7.11. Unknown or
Missing Race1 and Hispanic Ethnicity Over Time<o:p></o:p></a></h2>

<span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span><span style="mso-bookmark:X8bb539b4f8c8106409fcc822111649fd24d46a1"></span>
Year | Frequency   Unknown Race1 and Hispanic | Total Frequency | Percent Missing   Race1 and Hispanic
-- | -- | -- | --
2008 | 10 | 77 | 13.0
2009 | 10 | 3,692 | 0.3
2010 | 6 | 110 | 5.5
2011 | 11 | 22 | 50.0
2012 | 9 | 14,051 | 0.1
2013 | 3 | 40,255 | 0.0
2014 | 876 | 74,846 | 1.2
2015 | 766 | 14,154 | 5.4
2016 | 726 | 104 | 698.1
2017 | 864 | 19,125 | 4.5
2018 | 1,401 | 120 | 1,167.5
2019 | 2,381 | 24,835 | 9.6
2020 | 8,685 | 80 | 10,856.2
2021 | 630 | 12,495 | 5.0

**Comment by CartWill** [comment]
Migrated issues over to different Github repo : https://github.com/ACCORDSD2VDEV/CHORDS-QA/issues/45
