### ISSUE TITLE
Error at DH

### ISSUE THREAD

**Issue by zuckerr** [UCCC/CHORDS-QA#13]
New error/email from Ken at Denver Health:

Error: nanodbc/nanodbc.cpp:950: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Cannot open database "VDW.aligned" requested by the login. The login failed.

Any advice? Maybe VDW.aligned. (with a second period)?  Not sure why this would fail…

**Comment by bryantmdoyle** [comment]
The windows login being used to run the QA has to have permissions on the VDW.align database

Bryant

On Apr 6, 2018, at 7:19 AM, zuckerr <notifications@github.com<mailto:notifications@github.com>> wrote:


New error/email from Ken at Denver Health:

Error: nanodbc/nanodbc.cpp:950: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Cannot open database "VDW.aligned" requested by the login. The login failed.

Any advice? Maybe VDW.aligned. (with a second period)? Not sure why this would fail…
