### ISSUE TITLE
Error with DB connection at MHCD

### ISSUE THREAD

**Issue by CJMcKinney** [UCCC/CHORDS-QA#14]
I am getting the following error running the package for P2 files:

Quitting from lines 19-35 (P2.Rmd) 
Error: nanodbc/nanodbc.cpp:950: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Cannot open database "CHORDSlive.dbo" requested by the login. The login failed. 

I am realizing two possible issues, 1) the CHORDSlive.dbo is both the DB and the schema, maybe only the schema is needed. 2) Is there anything else I would need to provide to login to the account.

Thanks,  --CJ

**Comment by vtmacox** [comment]
This indicates that you do not have the credentials to access the VDW.  The package uses the credentials of of the logged in user (so whomever is logged in to the current computer and running the program) to run the report.  This is done passively, so no user name or passwords are prompted.

**Comment by CJMcKinney** [comment]
I have owner level permission for the CHORDSlive DB, reviewing the logs, your program is picking up the user name correctly, but it is not liking the DB name 'CHORDSlive.dbo' .  Does the schema need to be part of the name?  I never login with the name in that format, only the 'CHORDSlive' DB name.

**Comment by vtmacox** [comment]
The DB Server Name and DB Name have to match what you would use for a typical SQL query.  Make sure the case is correct as this matters in R.

**Comment by CJMcKinney** [comment]
Can CHORDSlive then be added to the selections as a DB choice?

**Comment by vtmacox** [comment]
Is this a DB Server Name or a DB Name.  Also, is the spelling and capitalization exactly correct?  I can add it as an option once you've verified this info.

**Comment by CJMcKinney** [comment]
The Server is BI01 and the DB is CHORDSlive

Thanks

________________________________

**Comment by vtmacox** [comment]
This DB name has been added to the package.  Redownload and install the package and you will be able to select this name from the dropdown list.
