### ISSUE TITLE
SQL Error with MHCD run

### ISSUE THREAD

**Issue by CJMcKinney** [UCCC/CHORDS-QA#15]
the connection to the datbase is working fine now, but I am getting the following error now:

Quitting from lines 63-120 (P2.Rmd) 
Error: <SQL> 'select count(*) as nrows, 
	count(distinct person_id) as npats,
  'RESULT_DT' as fieldname,
	min(result_dt) as mindt,
	max(result_dt) as maxdt
	from lab_results'
  nanodbc/nanodbc.cpp:1587: 42S22: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'result_dt'. 

I checked our LAB_RESULTS table and we have the field RESULTS_DT which is also consistent with the data dictionary we have, but the RMD script is searching for RESULT_DT.  Please advise on how we should move forward.  Thanks

**Comment by zuckerr** [comment]
Hi CJ, I've identified a conflict in our documentation here. Let me check with someone and I'll post here with an update.

**Comment by zuckerr** [comment]
CJ - this is an error from our end, where the data dictionary we asked sites to fill out conflicts with our data model manual and our DDL. In LAB_RESULTS, I see two fields in conflict - RESULT_DT and RESULT_TM are the proper names for the fields. I'm sorry that we have this error and we'll be fixing our documentation. Is it possible to change those field names?

**Comment by CJMcKinney** [comment]
Thanks for checking on the conflict.  We will make the updates on our end, they should be pretty straightforward.
