### ISSUE TITLE
Add argument that allows for SQL server login

### ISSUE THREAD

**Issue by vtmacox** [UCCC/CHORDS-QA#16]
Need to add an argument that allows the user to select either Windows Authentication or SQL server login.  First we need to see if users know which login method they use.

**Comment by zuckerr** [comment]
I sent emails to several sites to try to get an idea of this, I will let you know what I hear back.

**Comment by zuckerr** [comment]
CCMCN (represents 6 FQHC sites) - Windows authentication.

**Comment by zuckerr** [comment]
CHCO - Windows authentication.

**Comment by zuckerr** [comment]
DH - Windows authentication
UCHealth (when up and running) - Windows authentication. 

At the very least - no site has had trouble identifying which log in they use.

**Comment by vtmacox** [comment]
It looks like maybe only KP is using the SQL Server login.  If that is the case, I can put a note in indicating that most users will be using the Windows authentication and then default to that method.

**Comment by zuckerr** [comment]
Sounds good, and then would David (and anyone else who may happen to use SQL server login in the future) just see a note indicated that they should use that login instead?

**Comment by vtmacox** [comment]
No.  There is no way for me to tell who should use what login.  The user will have to know what that is.  There will be a radio button with the options "Windows Authentication" and "SQL Login".  Someone like David would have to know they use the SQL Login and select that response.

**Comment by zuckerr** [comment]
Got it, based on the responses it seems like folks will be able to make that selection no problem.

**Comment by CartWill** [comment]
Old.  Fixed by changing how connection string gets built.
