### ISSUE TITLE
KP warning messages

### ISSUE THREAD

**Issue by zuckerr** [UCCC/CHORDS-QA#17]
Hi Matt, KP is trying a new run of the QA package. Mark was checking in on Step 1 - I think he's good to go, I usually see similar error messages and it looks like he ended up with the downloaded packages installed. Do you see anything amiss with the following:

I get a slew of Warning messages:
package ‘mime’ successfully unpacked and MD5 sums checked
package ‘mime’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e6702d692f64\mime’ to ‘C:\Program Files\R\R-3.1.2\library\mime’
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e6702d692f64\mime’ to ‘C:\Program Files\R\R-3.1.2\library\mime’
package ‘curl’ successfully unpacked and MD5 sums checked
package ‘curl’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e6704ffb7a4c\curl’ to ‘C:\Program Files\R\R-3.1.2\library\curl’
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e6704ffb7a4c\curl’ to ‘C:\Program Files\R\R-3.1.2\library\curl’
package ‘openssl’ successfully unpacked and MD5 sums checked
package ‘openssl’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e67037c22655\openssl’ to ‘C:\Program Files\R\R-3.1.2\library\openssl’
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e67037c22655\openssl’ to ‘C:\Program Files\R\R-3.1.2\library\openssl’
package ‘httr’ successfully unpacked and MD5 sums checked
package ‘httr’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e670140935f9\httr’ to ‘C:\Program Files\R\R-3.1.2\library\httr’
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e670140935f9\httr’ to ‘C:\Program Files\R\R-3.1.2\library\httr’
package ‘jsonlite’ successfully unpacked and MD5 sums checked
package ‘jsonlite’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e6703f855f2a\jsonlite’ to ‘C:\Program Files\R\R-3.1.2\library\jsonlite’
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e6703f855f2a\jsonlite’ to ‘C:\Program Files\R\R-3.1.2\library\jsonlite’
package ‘git2r’ successfully unpacked and MD5 sums checked
package ‘git2r’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e6704449442a\git2r’ to ‘C:\Program Files\R\R-3.1.2\library\git2r’
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e6704449442a\git2r’ to ‘C:\Program Files\R\R-3.1.2\library\git2r’
package ‘devtools’ successfully unpacked and MD5 sums checked
package ‘devtools’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e67044515c34\devtools’ to ‘C:\Program Files\R\R-3.1.2\library\devtools’
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.1.2\library\file4e67044515c34\devtools’ to ‘C:\Program Files\R\R-3.1.2\library\devtools’

The downloaded binary packages are in
        C:\Users\Q936303\AppData\Local\Temp\Rtmp00V9Pq\downloaded_packages

The downloaded binary packages are in
        C:\Users\Q936303\AppData\Local\Temp\Rtmp00V9Pq\downloaded_packages

**Comment by vtmacox** [comment]
Try restarting R and updating packages again.  I don't think this should cause problems.

**Comment by zuckerr** [comment]
Thanks Matt. Mark also noted that KP has them on an older version of RStudio, he's asking IT to get him the newer version and hopefully that will address some of these messages too.
