### ISSUE TITLE
Issue for QA package at Kaiser

### ISSUE THREAD

**Issue by zuckerr** [UCCC/CHORDS-QA#19]
Message from Mark Gray at KP. Matt any ideas on this? 

![image](https://user-images.githubusercontent.com/16942744/42833407-3ee8dbbe-89b1-11e8-9397-e56fc0558c33.png)

**Comment by vtmacox** [comment]
This looks like an R issue and not a package issue.  It looks like they are using a fairly outdated version of R, I would start by installing the most updated version of R.

**Comment by CartWill** [comment]
Old.
