### ISSUE TITLE
Change DH server name in dropdown

### ISSUE THREAD

**Issue by zuckerr** [UCCC/CHORDS-QA#20]
please delete the server name starting with ‘uat’ from the available options and add the following server name: DWPHSQL01

**Comment by vtmacox** [comment]
I added the server name to the drop down list.  Please check to make sure that it works.  If it does, please close this issue

**Comment by zuckerr** [comment]
Hi Matt, thanks so much! Ken shared the following response: 
![image](https://user-images.githubusercontent.com/16942744/47113475-63c88800-d216-11e8-82e3-3e103915cfc1.png)

**Comment by vtmacox** [comment]
I think I've fixed the problem.  See if that works and let me know.

**Comment by zuckerr** [comment]
From Ken: Something changed so that I can’t access the right database anymore.  As opposed to VDW_aligned I can only access VDW.aligned

**Comment by vtmacox** [comment]
One last time (maybe).  I think I fixed the issue.  Really sorry about this.

**Comment by zuckerr** [comment]
No no trouble at all! Thanks for sticking with us. Will let you know what Ken says.

**Comment by zuckerr** [comment]
Update from Ken:
P1 ran successfully.  Unfortunately, P2 didn’t finish.  Here’s the error:

Quitting from lines 64-121 (P2.Rmd) 
Error in bind_rows_(x, .id) : 
  Column `mindt` can't be converted from POSIXct, POSIXt to character
In addition: Warning messages:
1: In bind_rows_(x, .id) :
  binding factor and character vector, coercing into character vector
2: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector

**Comment by vtmacox** [comment]
I can't replicate this error.  This part of the code hasn't changed in quite some time.  It could indicate there is a problem with the data.  It may be that the data aren't in the correct date format.  I would make sure that any of the date variable used in Table 2 are all correct.

**Comment by vtmacox** [comment]
I've updated the code so that everything runs on my end.  I would double check the data source to make sure that is correct.

**Comment by CartWill** [comment]
Old - Closing out.
