### ISSUE TITLE
Might be the code, might be the data

### ISSUE THREAD

**Issue by k-scott** [UCCC/CHORDS-QA#6]
The following issues jumped out to us, though it's not clear whether these have to do with the way the QA program is running or whether they are issues with our data.  Just in case it's the former, I created this issue.  We can delete if we figure out it's the data.

- P1 Figure 6
- P1 has about 101k with missing county/state
- HEP_C_RNA figure on P2, page 9
- LDL figure on P2, page 11
- Pregnancy figure on P2, Page 12

**Comment by CartWill** [comment]
Old
