### ISSUE TITLE
Dropdown menu

### ISSUE THREAD

**Issue by k-scott** [UCCC/CHORDS-QA#8]
Not sure whether this is actually an issue, but the dropdown selection VDW.dbo didn’t work for me (even though I think that’s the one I provided you).  The VDW selection did work.  Like I said in my earlier e-mail, the VDW.dbo extension is what I use in my SQL code when I’m writing my queries.

**Comment by CartWill** [comment]
Old.  Fixed by removing the drop-down in favor of textbox.
