### ISSUE TITLE
P1 Coding additions

### ISSUE THREAD

**Issue by zuckerr** [UCCC/CHORDS-QA#81]
Table/Figure | Issue
-- | --
P1 |  
Table 2 | Add Encounter fields to unknown/missing table: Department, Facility Code
Table 2 | Add fields for BENEFITS table
Table 3 | Add Encounter Table to Table 3
Tables   12-Figure 4b | Distinguish between billing and PL diagnoses for these checks?

**Comment by CartWill** [comment]
Resolved Table 2 and 3 issues described.  Need to know what the expectations are for Table 12 and Figure 4b

**Comment by CartWill** [comment]
@emilybacon can you provide some more details on what the tables should look like for Table 12/Figure 4b?

**Comment by emilybacon** [comment]
I think we should limit all diagnosis tables to only include billing diagnoses (so dx_origin="BI"). This includes the following tables:

- The counts listed under "Examination of the Diagnoses Table"
- Table 12
- Table 13
- Figure 4a
- Figure 4b

**Comment by emilybacon** [comment]
Will can you confirm whether the diagnoses in the tables/figures above are now limited to billing only? That's the only remaining change for this issue.

**Comment by emilybacon** [comment]
TOP PRIORITY

**Comment by CartWill** [comment]
@emilybacon ready for testing.
