### ISSUE TITLE
P2 Coding Additions 

### ISSUE THREAD

**Issue by zuckerr** [UCCC/CHORDS-QA#82]
P2 |  
-- | --
Table 1 | Add PRO_Resoponses
Table 2 | Add Benefits table fields to missing/null - particularly for date
Table 2 | Add PRO_Responses
Table 12 | Before table 12, add some descriptive info about # of records in provider   table, since it isn't incuded in Table 1

**Comment by CartWill** [comment]
@emilybacon for P2 Table 2 PRO_RESPONSES what columns should be evaluated for missingness?

**Comment by emilybacon** [comment]
Variables from PRO_RESPONSES to be evaluated for missingness:
PRO_ID
QUESTION_ID
PERSON_ID
RESPONSE_DATE
RESPONSE_TIME
ENC_ID

**Comment by emilybacon** [comment]
Disregard the second row about benefits data in the comment above since that's in the P1 report.

**Comment by emilybacon** [comment]
TOP PRIORITY

**Comment by CartWill** [comment]
@emilybacon ready for testing.
