### ISSUE TITLE
Telehealth P2 Updates

### ISSUE THREAD

**Issue by zuckerr** [UCCC/CHORDS-QA#84]
1. Expand Table 9 to include new encounter types

2. Add new Figure 9a 
This line graph figure should contain the information in Table 9 but broken down by month. We’d want to do all months starting Jan 2019 to present (most recent available data). We’d only want counts of encounters and counts of diagnoses but not procedures. We’d want a line graph, with a line for each ENCTYPE showing the count for months. 
(Or for now - just the SQL to pull this data - don't worry about the display of information in R until Carter takes this ticket)

**Comment by emilybacon** [comment]
I think these would still be good additions to the P2 report when you have time.
