### ISSUE TITLE
New screening tables

### ISSUE THREAD

**Issue by emilybacon** [UCCC/CHORDS-QA#87]
Attached in the Word doc is the code I used to write the screening QA. It creates 23 new tables (Table 19-Table 42). Some of this coding may not work with the changes to the reports over the past 6 months. In addition to incorporating the new tables, can we please implement the following changes to the code:

- Recode years so that it is a 4-year lookback rather than hard coded for each year.
- Add labels for the Question ID

I'm also attaching the excel document that we used to design the screening tables, which has output for what they looked like when I originally created them, in case that's helpful. 

[Detailed Screening QA Proposed Checks_3.19.20.xlsx](https://github.com/UCCC/CHORDS-QA/files/5278637/Detailed.Screening.QA.Proposed.Checks_3.19.20.xlsx)

[Screening QA_9.24.20.docx](https://github.com/UCCC/CHORDS-QA/files/5278621/Screening.QA_9.24.20.docx)

**Comment by CartWill** [comment]
@emilybacon There are two queries selecting into the tab19 dataframe.  The second query will completely replace the results form the first.  Can we delete the first query?

**Comment by emilybacon** [comment]
Yes, that's correct. We no longer need the old Table 19 because it wasn't very useful. Thanks!

**Comment by CartWill** [comment]
@emilybacon I put in some of the changes around P2 Table 20.  If you could take a look and let me know it it's looking OK.  It should be year independent now where it will pull use the current year as  the base and then pull the past 4 years in if they exist.

**Comment by emilybacon** [comment]
Let's prioritize the following tables for now, and fill in the others later:
Tables 19-24, 30, 35, 40-42

**Comment by CartWill** [comment]
@emilybacon I added tables 19-24 to the dev branch.  Can you try it out when you have a chance?

**Comment by emilybacon** [comment]
I'm seeing errors for tables 20-22, and tables 23 and 24 don't populate. See below. As always, could be an issue on my end so let me know what you think or when I should re-run.

![image](https://user-images.githubusercontent.com/44174428/101080467-12022980-3566-11eb-8709-0698caf4dc79.png)
![image](https://user-images.githubusercontent.com/44174428/101080546-247c6300-3566-11eb-9ae7-b7396a741b0f.png)
![image](https://user-images.githubusercontent.com/44174428/101080618-3fe76e00-3566-11eb-91eb-24d51a793b7b.png)

**Comment by CartWill** [comment]
@emilybacon I added some more code to deal with if the PRO_QUESTIONS table doesn't exist.  Can you give it another try?

**Comment by emilybacon** [comment]
![image](https://user-images.githubusercontent.com/44174428/101189544-71b70e00-3614-11eb-8a18-e12973dd7f0f.png)
Looking good! DH doesn't populate the first two questions, so this looks accurate.

**Comment by CartWill** [comment]
@emilybacon I added the tables covering PHQ-9 to the P2 report if you want to take a look.  Also since it's a new year, you should see the code roll over to start with 2021

**Comment by CartWill** [comment]
@emilybacon for table 35, it looks like some of the expected columns aren't in the query. 

```
tab35 <- odbc::dbGetQuery(con, 
        paste0("select question_id,
	  count(distinct response_id) as nresponse,
	  SUM(CASE WHEN RESPONSE_TEXT IS NULL THEN 1 ELSE 0 END) as resp_text_null,
	  count(distinct response_id) - count(distinct enc_id) as ndup,
	  count(distinct enc_id) as nenc,
	  count(distinct person_id) as nperson
	  from ", pro_responses,"
	  where pro_id = 'CHORDS-7'
      group by question_id"))

	  
tab35$pct_high_response <- round(100*tab35$n_high_scores/tab35$nresponse,1)

```

should the min_resval, max_resval, mean_resval, and n_high_scores be part of the query and look like table 30 or should the columns be dropped?

```
tab30 <- odbc::dbGetQuery(con, 
        paste0("select question_id,
	  count(distinct response_id) as nresponse,
	  SUM(CASE WHEN RESPONSE_NUM IS NULL THEN 1 ELSE 0 END) as resp_num_null,
	  count(distinct response_id) - count(distinct enc_id) as ndup,
	  count(distinct enc_id) as nenc,
	  count(distinct person_id) as nperson,
	  min(response_num) as min_resval,
	  max(response_num) as max_resval,
	  avg(response_num) as mean_resval,
	  sum(CASE WHEN RESPONSE_NUM > 2 and question_id <>8 then 1 
	           WHEN response_num > 15 and question_id=8 then 1
	           ELSE 0 end) as n_high_scores
	  from ", pro_responses,"
	  where pro_id = 'CHORDS-6'
      group by question_id"))

tab30$pct_high_response <- round(100*tab30$n_high_scores/tab30$nresponse,1)
```

**Comment by emilybacon** [comment]
Thanks for this great progress. A few comments in here:

- Attached images highlight some issues for PHQ-2 and PHQ-9 data.
- Rollover to 2021 looks good!
- I had copied the wrong column names for Table 35. It's all character responses, so columns should be: Total # of   responses | # of missing   responses | # of duplicates | # of unique   encounters | # of unique   patients
![image](https://user-images.githubusercontent.com/44174428/105750449-0138b900-5f02-11eb-9818-7aac1ae2395b.png)
![image](https://user-images.githubusercontent.com/44174428/105750516-13b2f280-5f02-11eb-8ace-273d130e9d34.png)
![image](https://user-images.githubusercontent.com/44174428/105750576-275e5900-5f02-11eb-8f15-ea158982b78d.png)

**Comment by CartWill** [comment]
@emilybacon so the first query for a survey, like Table 19, is a distinct of person_ids regardless of the year it was taken so a person is only counted once regardless of the year they took the survey.  The other queries, like for table 22 where we have the year broken out, it's a district count of person_ids by year for a specific number of years.  A person is counted once per year. If they took the same survey more than once across years, they get counted once for each year they took a survey.

I committed some changes today that have the updates for GAD-7 and PREPARE.  That should be all of the tables from the word document.

**Comment by emilybacon** [comment]
Ah, thanks so much for clarifying. Makes perfect sense. 

I'm pretty sure this was my mistake from the mockup but I realized that the final screening tool is spelled "PRAPARE" rather than the actual word prepare. I'm going to go in and change that in the titles.

Sending you an email about remaining screening stuff now.
