### ISSUE TITLE
Add DX_CODETYPE to P1 Table 2 

### ISSUE THREAD

**Issue by emilybacon** [UCCC/CHORDS-QA#88]
Add DX_CODETYPE field from the DIAGNOSES table to P1 report, Table 2: Missingness Variables across P1 Tables. 

This is an important field in many of our queries and I realized that we don't know whether it is fully populated across data partners.

**Comment by emilybacon** [comment]
TOP PRIORITY

**Comment by CartWill** [comment]
@emilybacon ready for testing.
