### ISSUE TITLE
Telehealth table 7.14 error

### ISSUE THREAD

**Issue by emilybacon** [UCCC/CHORDS-QA#89]
Here's the error message:
Quitting from lines 2242-2348 (P1.Rmd) 
Error in format.data.frame(data = tab7.14a, big.mark = ",") : 
  argument "x" is missing, with no default

**Comment by emilybacon** [comment]
![image](https://user-images.githubusercontent.com/44174428/98716148-4fe5a680-2348-11eb-975e-e263bcea7f32.png)

**Comment by CartWill** [comment]
@emilybacon I had the format in the wrong place.  Should be fixed now.
