### ISSUE TITLE
BENEFIT table additions

### ISSUE THREAD

**Issue by emilybacon** [UCCC/CHORDS-QA#93]
Attached is the excel file with the 4 new BENEFIT table mockups. Happy to run the SQL code anytime.
[New Benefits QA Table Shells_2.8.21.xlsx](https://github.com/UCCC/CHORDS-QA/files/5968533/New.Benefits.QA.Table.Shells_2.8.21.xlsx)

**Comment by CartWill** [comment]
@emilybacon These are in the code now to test.
