### ISSUE TITLE
Final fixes for report run - March 2021

### ISSUE THREAD

**Issue by emilybacon** [UCCC/CHORDS-QA#94]
P1 Table 10: I think the last row should be titled "Telehealth Video" or "Other Telehealth"
![image](https://user-images.githubusercontent.com/44174428/109569954-833e7380-7aa6-11eb-929e-5083c34932e1.png)

**Comment by emilybacon** [comment]
As you mentioned, TimeTest issue is coming up:
![image](https://user-images.githubusercontent.com/44174428/109570131-d1ec0d80-7aa6-11eb-872f-efe1a6ddab1a.png)

**Comment by emilybacon** [comment]
P2 Report: Remove BENEFIT table from Table 1 and Table 2 (It's already in P1 report) - sorry about that!

**Comment by CartWill** [comment]
@emilybacon these changes should be ready now.
